version: '3.8'

services:
  strava-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FRONTEND_ENV=${FRONTEND_ENV}
    ports:
      - "80:80"
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ./backend:/backend:ro
    restart: unless-stopped
    networks:
      - strava-network

networks:
  strava-network:
    driver: bridge
