#!/bin/bash

# GitHub Pages Quick Setup Script

echo "🚀 GitHub Pages Setup Helper"
echo "============================"
echo ""
echo "Your Strava fitness tracker is ready for GitHub Pages!"
echo ""
echo "🎯 NEXT STEP: Enable GitHub Pages"
echo ""
echo "1️⃣  Open this link in your browser:"
echo "   👉 https://github.com/matthewdlang18/strava/settings/pages"
echo ""
echo "2️⃣  Under 'Source', select:"
echo "   👉 'GitHub Actions' (NOT 'Deploy from a branch')"
echo ""
echo "3️⃣  Click 'Save'"
echo ""
echo "4️⃣  Wait for deployment (2-3 minutes)"
echo "   👉 Monitor at: https://github.com/matthewdlang18/strava/actions"
echo ""
echo "5️⃣  Access your app:"
echo "   👉 https://matthewdlang18.github.io/strava"
echo ""
echo "🎉 Features you'll get:"
echo "   ✅ Demo fitness data pre-loaded"
echo "   ✅ Interactive charts and maps"
echo "   ✅ Activity tracking dashboard"
echo "   ✅ Personal records & achievements"
echo "   ✅ Data export functionality"
echo "   ✅ Mobile-responsive design"
echo ""
echo "💡 This runs 100% in your browser - no servers needed!"
echo ""
read -p "Press Enter when you've enabled GitHub Pages..."
echo ""
echo "🔍 Checking if your site is live..."
echo "   If it's not ready yet, wait a few more minutes"
echo "   The workflow needs time to build and deploy"
echo ""
echo "🎯 Your app URL: https://matthewdlang18.github.io/strava"
echo ""
echo "🎊 Enjoy your free, professional fitness tracker!"
